# Generated by Django 6.0.1 on 2026-02-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0031_committeeparticipationsubstitute'),
        ('district', '0032_sessionexcuse'),
    ]

    operations = [
    ]
