# Generated by Django 6.1 on 2026-09-03 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_initial_committee_membership_periods(apps, schema_editor):
    CommitteeMember = apps.get_model('district', 'CommitteeMember')
    CommitteeMembershipPeriod = apps.get_model('district', 'CommitteeMembershipPeriod')
    for member in CommitteeMember.objects.all().iterator():
        end_date = None
        if not member.is_active:
            end_date = member.updated_at.date() if member.updated_at else member.joined_date
        CommitteeMembershipPeriod.objects.create(
            member=member,
            start_date=member.joined_date,
            end_date=end_date,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0039_rename_local_to_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMembershipPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day of this membership period')),
                ('end_date', models.DateField(blank=True, help_text='Last day of this membership period (leave empty if currently active)', null=True)),
                ('member', models.ForeignKey(help_text='Committee membership this period belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='district.committeemember')),
            ],
            options={
                'verbose_name': 'Membership period',
                'verbose_name_plural': 'Membership periods',
                'ordering': ['-start_date', '-pk'],
            },
        ),
        migrations.RunPython(create_initial_committee_membership_periods, migrations.RunPython.noop),
    ]
