# Generated by Django 5.2 on 2025-08-29 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('local', '0006_party_local_alter_party_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the motion', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the motion')),
                ('motion_type', models.CharField(choices=[('resolution', 'Resolution'), ('amendment', 'Amendment'), ('proposal', 'Proposal'), ('inquiry', 'Inquiry'), ('recommendation', 'Recommendation'), ('budget', 'Budget'), ('policy', 'Policy'), ('other', 'Other')], default='proposal', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('amended', 'Amended'), ('withdrawn', 'Withdrawn'), ('tabled', 'Tabled')], default='draft', max_length=20)),
                ('rationale', models.TextField(blank=True, help_text='Rationale and background for the motion')),
                ('expected_impact', models.TextField(blank=True, help_text='Expected impact if motion is approved')),
                ('fiscal_impact', models.TextField(blank=True, help_text='Financial impact of the motion')),
                ('timeline', models.TextField(blank=True, help_text='Proposed timeline for implementation')),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.JSONField(blank=True, default=dict)),
                ('group', models.ForeignKey(help_text='Group proposing this motion', on_delete=django.db.models.deletion.CASCADE, related_name='motions', to='group.group')),
                ('parties', models.ManyToManyField(blank=True, help_text='Parties supporting this motion', related_name='motions', to='local.party')),
                ('session', models.ForeignKey(help_text='Session where this motion will be presented', on_delete=django.db.models.deletion.CASCADE, related_name='motions', to='local.session')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_motions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motion',
                'verbose_name_plural': 'Motions',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='MotionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='motion_attachments/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('spreadsheet', 'Spreadsheet'), ('presentation', 'Presentation'), ('other', 'Other')], default='document', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='motion.motion')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motion Attachment',
                'verbose_name_plural': 'Motion Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MotionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_public', models.BooleanField(default=True, help_text='Whether this comment is visible to all users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_comments', to=settings.AUTH_USER_MODEL)),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='motion.motion')),
            ],
            options={
                'verbose_name': 'Motion Comment',
                'verbose_name_plural': 'Motion Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('abstain', 'Abstain'), ('absent', 'Absent')], max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Reason for the vote')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='motion.motion')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motion Vote',
                'verbose_name_plural': 'Motion Votes',
                'ordering': ['-voted_at'],
                'unique_together': {('motion', 'voter')},
            },
        ),
    ]
