# Generated by Django 5.2 on 2025-08-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motion',
            name='expected_impact',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='fiscal_impact',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='rationale',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='timeline',
        ),
    ]
