# Generated by Django 5.2 on 2025-08-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0002_remove_motion_expected_impact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motion',
            name='priority',
        ),
    ]
