# Generated by Django 5.2 on 2025-08-29 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0007_alter_termseatdistribution_options_and_more'),
        ('motion', '0003_remove_motion_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='committee',
            field=models.ForeignKey(blank=True, help_text='Committee this motion is assigned to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motions', to='local.committee'),
        ),
        migrations.AlterField(
            model_name='motion',
            name='motion_type',
            field=models.CharField(choices=[('resolution', 'Resolution'), ('general', 'General motion')], default='proposal', max_length=20),
        ),
        migrations.AlterField(
            model_name='motion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
    ]
