# Generated by Django 5.2 on 2025-08-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0004_motion_committee_alter_motion_motion_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motion',
            name='description',
        ),
        migrations.AddField(
            model_name='motion',
            name='rationale',
            field=models.TextField(blank=True, help_text='Rationale and justification for the motion'),
        ),
        migrations.AddField(
            model_name='motion',
            name='text',
            field=models.TextField(blank=True, help_text='Detailed text of the motion'),
        ),
    ]
