# Generated by Django 5.2 on 2025-08-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0005_remove_motion_description_motion_rationale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motion',
            name='motion_type',
            field=models.CharField(choices=[('resolution', 'Resolution'), ('general', 'General motion')], default='general', max_length=20),
        ),
    ]
