# Generated by Django 5.2 on 2025-08-31 13:26

from django.db import migrations


def populate_status_history(apps, schema_editor):
    """Populate status history for existing motions"""
    Motion = apps.get_model('motion', 'Motion')
    MotionStatus = apps.get_model('motion', 'MotionStatus')
    
    for motion in Motion.objects.all():
        # Create initial status entry based on current status
        MotionStatus.objects.create(
            motion=motion,
            status=motion.status,
            changed_by=motion.submitted_by,
            reason='Initial status'
        )


def reverse_populate_status_history(apps, schema_editor):
    """Reverse the status history population"""
    MotionStatus = apps.get_model('motion', 'MotionStatus')
    MotionStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0007_motionstatus'),
    ]

    operations = [
        migrations.RunPython(populate_status_history, reverse_populate_status_history),
    ]
