# Generated by Django 5.2 on 2025-08-31 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0012_remove_session_time_fields'),
        ('motion', '0008_populate_status_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionstatus',
            name='committee',
            field=models.ForeignKey(blank=True, help_text="Committee when status is 'refer_to_committee'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motion_status_changes', to='local.committee'),
        ),
        migrations.AlterField(
            model_name='motion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('refer_to_committee', 'Refer to Committee'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='motionstatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('refer_to_committee', 'Refer to Committee'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], max_length=20),
        ),
    ]
