# Generated by Django 5.2 on 2025-08-31 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0012_remove_session_time_fields'),
        ('motion', '0009_motionstatus_committee_alter_motion_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionGroupDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('abstain', 'Abstain'), ('withdraw', 'Withdraw'), ('refer_to_committee', 'Referred to Committee')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the group decision')),
                ('decision_time', models.DateTimeField(help_text='When the decision was made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(blank=True, help_text="Committee when decision is 'refer_to_committee'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motion_group_decisions', to='local.committee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motion_group_decisions_created', to=settings.AUTH_USER_MODEL)),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_decisions', to='motion.motion')),
            ],
            options={
                'verbose_name': 'Motion Group Decision',
                'verbose_name_plural': 'Motion Group Decisions',
                'ordering': ['-decision_time'],
            },
        ),
    ]
