# Generated by Django 5.2 on 2025-08-31 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0010_motiongroupdecision'),
        ('local', '0014_alter_sessionattachment_file_type'),
    ]

    operations = [
        # Add new fields
        migrations.AddField(
            model_name='motionvote',
            name='party',
            field=models.ForeignKey(
                help_text='Party casting the vote',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='motion_votes',
                to='local.party',
                null=True,  # Allow null temporarily for migration
            ),
        ),
        migrations.AddField(
            model_name='motionvote',
            name='approve_votes',
            field=models.PositiveIntegerField(default=0, help_text='Number of approve votes from this party'),
        ),
        migrations.AddField(
            model_name='motionvote',
            name='reject_votes',
            field=models.PositiveIntegerField(default=0, help_text='Number of reject votes from this party'),
        ),
        migrations.AddField(
            model_name='motionvote',
            name='abstain_votes',
            field=models.PositiveIntegerField(default=0, help_text='Number of abstain votes from this party'),
        ),
        migrations.AddField(
            model_name='motionvote',
            name='total_members',
            field=models.PositiveIntegerField(default=0, help_text='Total number of party members in the council'),
        ),
        migrations.AddField(
            model_name='motionvote',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the voting'),
        ),
        
        # Update unique constraint
        migrations.AlterUniqueTogether(
            name='motionvote',
            unique_together={('motion', 'party')},
        ),
        
        # Make party field non-nullable
        migrations.AlterField(
            model_name='motionvote',
            name='party',
            field=models.ForeignKey(
                help_text='Party casting the vote',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='motion_votes',
                to='local.party',
            ),
        ),
    ]
