# Generated by Django 5.2 on 2025-08-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0011_auto_20250831_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motionvote',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='motionvote',
            name='total_members',
        ),
        migrations.RemoveField(
            model_name='motionvote',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='motionvote',
            name='voter',
        ),
        migrations.AlterField(
            model_name='motiongroupdecision',
            name='decision',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('abstain', 'Abstain'), ('withdraw', 'Withdraw'), ('refer_to_committee', 'Refer to Committee')], max_length=20),
        ),
    ]
