# Generated by Django 5.2 on 2025-08-31 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0012_remove_motionvote_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionvote',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Status change this vote is connected to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='motion.motionstatus'),
        ),
    ]
