# Generated by Django 5.2 on 2025-08-31 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0013_motionvote_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='motionvote',
            unique_together=set(),
        ),
    ]
