# Generated by Django 5.2.6 on 2025-10-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0014_remove_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motionvote',
            name='abstain_votes',
        ),
    ]
