# Generated by Django 5.2.7 on 2025-12-04 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0015_remove_abstain_votes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='interventions',
            field=models.ManyToManyField(blank=True, help_text='Wortmeldung: Users from the corresponding group who can speak in session', related_name='motion_interventions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motion',
            name='motion_type',
            field=models.CharField(choices=[('resolution', 'Resolutionsantrag'), ('general', 'General motion')], default='general', max_length=20),
        ),
    ]
