# Generated by Django 5.2.7 on 2025-12-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0016_add_interventions_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='session_rank',
            field=models.PositiveIntegerField(default=0, help_text='Rank/order of this motion within its session'),
        ),
    ]
