# Generated by Django 5.2.7 on 2025-12-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0017_add_session_rank_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('refer_to_committee', 'Refer to Committee'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('not_admitted', 'Nicht zugelassen')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='motionstatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('refer_to_committee', 'Refer to Committee'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('not_admitted', 'Nicht zugelassen')], max_length=20),
        ),
    ]
