# Generated by Django 5.2.7 on 2025-12-08 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_add_agenda_item'),
        ('local', '0017_add_committee_abbreviation'),
        ('motion', '0018_add_not_admitted_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the question', max_length=200)),
                ('text', models.TextField(blank=True, help_text='Detailed text of the question')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('answered', 'Answered'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_rank', models.PositiveIntegerField(default=0, help_text='Rank/order of this question within its session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(help_text='Group asking this question', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='group.group')),
                ('interventions', models.ManyToManyField(blank=True, help_text='Wortmeldung: Users from the corresponding group who can speak in session', related_name='question_interventions', to=settings.AUTH_USER_MODEL)),
                ('parties', models.ManyToManyField(blank=True, help_text='Parties supporting this question', related_name='questions', to='local.party')),
                ('session', models.ForeignKey(help_text='Session where this question will be presented', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='local.session')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-submitted_date'],
            },
        ),
    ]
