# Generated by Django 5.2.7 on 2025-12-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0019_add_question_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, help_text='Answer to the question'),
        ),
    ]
