# Generated by Django 5.2.7 on 2025-12-08 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0020_add_answer_field_to_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='question_attachments/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('spreadsheet', 'Spreadsheet'), ('presentation', 'Presentation'), ('other', 'Other')], default='document', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='motion.question')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Attachment',
                'verbose_name_plural': 'Question Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
