# Generated by Django 5.2.7 on 2025-12-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0021_add_question_attachment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('refer_to_committee', 'Refer to Committee'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('answered', 'Answered'), ('withdrawn', 'Withdrawn'), ('not_admitted', 'Nicht zugelassen')], default='draft', max_length=20),
        ),
    ]

