# Generated by Django 5.2.7 on 2025-12-08 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0022_add_motion_statuses_to_questions'),
        ('local', '0017_add_committee_abbreviation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('refer_to_committee', 'Refer to Committee'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('answered', 'Answered'), ('withdrawn', 'Withdrawn'), ('not_admitted', 'Nicht zugelassen')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the status change')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_status_changes', to=settings.AUTH_USER_MODEL)),
                ('committee', models.ForeignKey(blank=True, help_text="Committee when status is 'refer_to_committee'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_status_changes', to='local.committee')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='motion.question')),
            ],
            options={
                'verbose_name': 'Question Status',
                'verbose_name_plural': 'Question Statuses',
                'ordering': ['-changed_at'],
            },
        ),
    ]

