# Generated by Django 5.2.9 on 2025-12-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0023_add_question_status_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tag', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the tag name', unique=True)),
                ('color', models.CharField(default='#007bff', help_text='Color code for the tag (hex format)', max_length=7)),
                ('description', models.TextField(blank=True, help_text='Description of the tag')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='motion',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorizing this motion', related_name='motions', to='motion.tag'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorizing this question', related_name='questions', to='motion.tag'),
        ),
    ]
