# Generated by Django 5.2.9 on 2026-01-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0024_tag_motion_tags_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionvote',
            name='vote_type',
            field=models.CharField(choices=[('regular', 'Regular Vote'), ('refer_to_committee', 'Refer to Committee')], default='regular', help_text='Type of vote: regular or refer to committee', max_length=20),
        ),
        migrations.AlterField(
            model_name='motionvote',
            name='approve_votes',
            field=models.PositiveIntegerField(default=0, help_text='Number of votes in favor from this party'),
        ),
        migrations.AlterField(
            model_name='motionvote',
            name='reject_votes',
            field=models.PositiveIntegerField(default=0, help_text='Number of votes against from this party'),
        ),
    ]
