# Generated by Django 5.2.9 on 2026-01-17 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0020_add_committee_to_session'),
        ('motion', '0025_add_vote_type_to_motionvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionvote',
            name='outcome',
            field=models.CharField(blank=True, choices=[('adopted', 'Adopted'), ('rejected', 'Rejected'), ('tie', 'Tie'), ('referred', 'Referred to Committee'), ('not_referred', 'Not Referred')], help_text='Calculated outcome based on majority', max_length=20),
        ),
        migrations.AddField(
            model_name='motionvote',
            name='total_against',
            field=models.PositiveIntegerField(default=0, help_text='Total votes against across all parties (calculated)'),
        ),
        migrations.AddField(
            model_name='motionvote',
            name='total_favor',
            field=models.PositiveIntegerField(default=0, help_text='Total votes in favor across all parties (calculated)'),
        ),
        migrations.AddField(
            model_name='motionvote',
            name='vote_name',
            field=models.CharField(blank=True, help_text='Custom name/description for this voting round', max_length=200),
        ),
        migrations.AddField(
            model_name='motionvote',
            name='vote_round',
            field=models.CharField(blank=True, help_text="Voting round identifier (e.g., 'First Reading', 'Second Reading')", max_length=100),
        ),
        migrations.AddField(
            model_name='motionvote',
            name='vote_session',
            field=models.ForeignKey(blank=True, help_text='Session where this vote was cast', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motion_votes', to='local.session'),
        ),
    ]
