# Generated by Django 5.2.9 on 2026-01-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0026_add_multiple_votes_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motionvote',
            name='vote_round',
        ),
    ]
