# Generated by Django 6.0.1 on 2026-01-26 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0020_add_committee_to_session'),
        ('motion', '0028_add_voted_in_committee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('tabled', 'Tabled'), ('refer_to_committee', 'Refer to Committee'), ('voted_in_committee', 'Voted upon in Committee'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('not_admitted', 'Nicht zugelassen'), ('answered', 'Answered')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='motionstatus',
            name='committee',
            field=models.ForeignKey(blank=True, help_text="Committee when status is 'refer_to_committee' or 'voted_in_committee'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motion_status_changes', to='local.committee'),
        ),
        migrations.AlterField(
            model_name='motionstatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('tabled', 'Tabled'), ('refer_to_committee', 'Refer to Committee'), ('voted_in_committee', 'Voted upon in Committee'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('not_admitted', 'Nicht zugelassen'), ('answered', 'Answered')], max_length=20),
        ),
    ]
