# Generated by Django 6.0.1 on 2026-01-26 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0020_add_committee_to_session'),
        ('motion', '0029_add_tabled_and_answered_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionstatus',
            name='session',
            field=models.ForeignKey(blank=True, help_text="Session when status is 'tabled'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motion_status_changes', to='local.session'),
        ),
    ]
