# Generated by Django 6.0.1 on 2026-01-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0031_add_deleted_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('tabled', 'Tabled'), ('refer_to_committee', 'Refer to Committee'), ('refer_no_majority', 'Refer to Committee (no majority)'), ('voted_in_committee', 'Voted upon in Committee'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('not_admitted', 'Nicht zugelassen'), ('answered', 'Answered'), ('deleted', 'Deleted')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='motionstatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('tabled', 'Tabled'), ('refer_to_committee', 'Refer to Committee'), ('refer_no_majority', 'Refer to Committee (no majority)'), ('voted_in_committee', 'Voted upon in Committee'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('not_admitted', 'Nicht zugelassen'), ('answered', 'Answered'), ('deleted', 'Deleted')], max_length=20),
        ),
    ]
