# Generated by Django 6.0.1 on 2026-01-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0032_add_refer_no_majority_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionstatus',
            name='answer_pdf',
            field=models.FileField(blank=True, help_text="Written answer PDF (when status is 'answered')", null=True, upload_to='motion_answers/%Y/%m/%d/'),
        ),
    ]
