# Generated by Django 6.0.2 on 2026-02-16 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0020_remove_groupmeetingparticipation_group_groupmeetingparticipation_meeting_member_uniq_and_more'),
        ('local', '0033_merge_20260202_1418'),
        ('motion', '0034_rename_question_to_inquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-submitted_date'], 'verbose_name': 'Inquiry', 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='inquiryattachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Inquiry Attachment', 'verbose_name_plural': 'Inquiry Attachments'},
        ),
        migrations.AlterModelOptions(
            name='inquirystatus',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Inquiry Status', 'verbose_name_plural': 'Inquiry Statuses'},
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='answer',
            field=models.TextField(blank=True, help_text='Answer to the inquiry'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='group',
            field=models.ForeignKey(help_text='Group asking this inquiry', on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='group.group'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='interventions',
            field=models.ManyToManyField(blank=True, help_text='Wortmeldung: Users from the corresponding group who can speak in session', related_name='inquiry_interventions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='parties',
            field=models.ManyToManyField(blank=True, help_text='Parties supporting this inquiry', related_name='inquiries', to='local.party'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='session',
            field=models.ForeignKey(help_text='Session where this inquiry will be presented', on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='local.session'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='session_rank',
            field=models.PositiveIntegerField(default=0, help_text='Rank/order of this inquiry within its session'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorizing this inquiry', related_name='inquiries', to='motion.tag'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='text',
            field=models.TextField(blank=True, help_text='Detailed text of the inquiry'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='title',
            field=models.CharField(help_text='Title of the inquiry', max_length=200),
        ),
        migrations.AlterField(
            model_name='inquiryattachment',
            name='file',
            field=models.FileField(upload_to='inquiry_attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='inquiryattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inquirystatus',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inquirystatus',
            name='committee',
            field=models.ForeignKey(blank=True, help_text="Committee when status is 'refer_to_committee'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_status_changes', to='local.committee'),
        ),
    ]
