# Generated by Django 5.2 on 2025-09-16 16:46

from django.db import migrations


def fix_emailaddress_user_references(apps, schema_editor):
    """
    Fix EmailAddress records that reference auth_user instead of user_customuser.
    This migration ensures that all EmailAddress records point to the correct user table.
    """
    EmailAddress = apps.get_model('account', 'EmailAddress')
    CustomUser = apps.get_model('user', 'CustomUser')
    
    # Get all EmailAddress records
    email_addresses = EmailAddress.objects.all()
    
    for email_address in email_addresses:
        # Find the corresponding CustomUser by email
        try:
            custom_user = CustomUser.objects.get(email=email_address.email)
            # Update the user_id to point to the CustomUser
            email_address.user_id = custom_user.id
            email_address.save()
            print(f"Updated EmailAddress {email_address.id} to reference CustomUser {custom_user.id}")
        except CustomUser.DoesNotExist:
            print(f"Warning: No CustomUser found for email {email_address.email}")
            # Optionally delete the orphaned EmailAddress
            email_address.delete()
            print(f"Deleted orphaned EmailAddress {email_address.id}")


def reverse_fix_emailaddress_user_references(apps, schema_editor):
    """
    Reverse migration - this is not easily reversible, so we'll just pass.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_migrate_users_from_auth'),
        ('account', '0009_emailaddress_unique_primary_email'),
    ]

    operations = [
        migrations.RunPython(
            fix_emailaddress_user_references,
            reverse_fix_emailaddress_user_references,
        ),
    ]
