# Generated by Django 5.2.7 on 2025-10-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_fix_allauth_emailaddress_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='de', help_text='Preferred language for the interface', max_length=10),
        ),
    ]
