# Generated by Django 5.2.6 on 2025-10-04 23:48

from django.db import migrations


def create_fixed_roles(apps, schema_editor):
    """Create fixed roles for group membership"""
    Role = apps.get_model('user', 'Role')
    
    # Define the fixed roles
    fixed_roles = [
        {
            'name': 'Member',
            'description': 'Regular group member with basic participation rights',
            'permissions': {'permissions': ['group.view']},
            'is_active': True
        },
        {
            'name': 'Leader',
            'description': 'Group leader with decision-making authority and management rights',
            'permissions': {'permissions': ['group.view', 'group.edit', 'motion.create', 'motion.edit']},
            'is_active': True
        },
        {
            'name': 'Deputy Leader',
            'description': 'Assistant to the group leader with similar but limited authority',
            'permissions': {'permissions': ['group.view', 'motion.create', 'motion.edit']},
            'is_active': True
        }
    ]
    
    # Create or update each role
    for role_data in fixed_roles:
        role, created = Role.objects.get_or_create(
            name=role_data['name'],
            defaults=role_data
        )
        if not created:
            # Update existing role
            role.description = role_data['description']
            role.permissions = role_data['permissions']
            role.is_active = role_data['is_active']
            role.save()


def reverse_fixed_roles(apps, schema_editor):
    """Remove fixed roles (optional - you might want to keep them)"""
    Role = apps.get_model('user', 'Role')
    Role.objects.filter(name__in=['Member', 'Leader', 'Deputy Leader']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_language'),
    ]

    operations = [
        migrations.RunPython(create_fixed_roles, reverse_fixed_roles),
    ]
