# Generated by Django 6.0.2 on 2026-02-16 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_add_fixed_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSubscriptionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_subscription_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar subscription token',
                'verbose_name_plural': 'Calendar subscription tokens',
            },
        ),
    ]
