# Generated by Django 5.2 on 2025-08-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bezirk',
            new_name='Local',
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'ordering': ['name'], 'verbose_name': 'Local', 'verbose_name_plural': 'Locals'},
        ),
    ]
