# Generated by Django 5.2 on 2025-08-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_party_term_council_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='total_seats',
            field=models.PositiveIntegerField(default=0, help_text='Total number of seats in this term'),
        ),
        migrations.CreateModel(
            name='TermSeatDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of total seats (auto-calculated)', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_seats', to='local.party')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_distributions', to='local.term')),
            ],
            options={
                'verbose_name': 'Term Seat Distribution',
                'verbose_name_plural': 'Term Seat Distributions',
                'ordering': ['-seats', 'party__name'],
                'unique_together': {('term', 'party')},
            },
        ),
    ]
