# Generated by Django 5.2 on 2025-08-29 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0004_term_total_seats_termseatdistribution'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='council',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='council',
            name='local',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='council', to='local.local'),
        ),
    ]
