# Generated by Django 5.2 on 2025-08-29 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0005_alter_council_unique_together_alter_council_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='local',
            field=models.ForeignKey(blank=True, help_text='Local district this party belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='local.local'),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('name', 'local')},
        ),
    ]
