# Generated by Django 5.2 on 2025-08-29 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0006_party_local_alter_party_name_and_more'),
        ('user', '0002_role_alter_customuser_options_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termseatdistribution',
            options={'verbose_name': 'Term Seat Distribution', 'verbose_name_plural': 'Term Seat Distributions'},
        ),
        migrations.RemoveField(
            model_name='termseatdistribution',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='termseatdistribution',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='party',
            name='color',
            field=models.CharField(default='#007bff', help_text='Hex color code for the party', max_length=7),
        ),
        migrations.AlterField(
            model_name='party',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='local.local'),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='party',
            name='short_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='agenda',
            field=models.TextField(blank=True, help_text='Agenda items for the session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='council',
            field=models.ForeignKey(help_text='Council this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='local.council'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Actual end time of the session', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.CharField(blank=True, help_text='Location where the session will be held', max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='minutes',
            field=models.TextField(blank=True, help_text='Minutes from the session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='scheduled_date',
            field=models.DateTimeField(help_text='Scheduled date and time of the session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('regular', 'Regular Session'), ('special', 'Special Session'), ('emergency', 'Emergency Session'), ('committee', 'Committee Meeting'), ('public_hearing', 'Public Hearing'), ('workshop', 'Workshop')], default='regular', help_text='Type of session', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Actual start time of the session', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', help_text='Current status of the session', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Term this session belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='local.term'),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(help_text='Title of the session', max_length=200),
        ),
        migrations.AlterField(
            model_name='termseatdistribution',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_distributions', to='local.party'),
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the committee', max_length=200)),
                ('committee_type', models.CharField(choices=[('standing', 'Standing Committee'), ('ad_hoc', 'Ad Hoc Committee'), ('special', 'Special Committee'), ('working_group', 'Working Group'), ('task_force', 'Task Force')], default='standing', help_text='Type of committee', max_length=20)),
                ('description', models.TextField(blank=True, help_text="Description of the committee's purpose and responsibilities")),
                ('chairperson', models.CharField(blank=True, help_text='Name of the committee chairperson', max_length=100)),
                ('meeting_schedule', models.TextField(blank=True, help_text="Regular meeting schedule (e.g., 'First Monday of each month')")),
                ('is_active', models.BooleanField(default=True, help_text='Whether the committee is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('council', models.ForeignKey(help_text='Council this committee belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='local.council')),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
                'ordering': ['name'],
                'unique_together': {('name', 'council')},
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chairperson', 'Chairperson'), ('vice_chairperson', 'Vice Chairperson'), ('secretary', 'Secretary'), ('member', 'Member'), ('ex_officio', 'Ex Officio Member'), ('consultant', 'Consultant')], default='member', help_text='Role of the user in the committee', max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True, help_text='Date when the user joined the committee')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the membership is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the membership')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.JSONField(blank=True, default=dict)),
                ('committee', models.ForeignKey(help_text='Committee the user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='local.committee')),
                ('user', models.ForeignKey(help_text='User who is a member', on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to='user.customuser')),
            ],
            options={
                'verbose_name': 'Committee Member',
                'verbose_name_plural': 'Committee Members',
                'ordering': ['-joined_date'],
                'unique_together': {('committee', 'user')},
            },
        ),
    ]
