# Generated by Django 5.2 on 2025-08-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0007_alter_termseatdistribution_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='meeting_schedule',
        ),
    ]
