# Generated by Django 5.2 on 2025-08-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0008_remove_committee_meeting_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='committee_type',
            field=models.CharField(choices=[('Ausschuss', 'Ausschuss'), ('Kommission', 'Kommission')], default='standing', help_text='Type of committee', max_length=20),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='role',
            field=models.CharField(choices=[('chairperson', 'Chairperson'), ('vice_chairperson', 'Vice Chairperson'), ('member', 'Member')], default='member', help_text='Role of the user in the committee', max_length=20),
        ),
    ]
