# Generated by Django 5.2 on 2025-08-30 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0009_alter_committee_committee_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='council',
            name='description',
        ),
    ]
