# Generated by Django 5.2 on 2025-08-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0010_remove_council_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('regular', 'Regular Session'), ('special', 'Special Session')], default='regular', help_text='Type of session', max_length=20),
        ),
    ]
