# Generated by Django 5.2 on 2025-08-30 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0011_remove_session_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_time',
        ),
    ]
