# Generated by Django 5.2 on 2025-08-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0013_sessionattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionattachment',
            name='file_type',
            field=models.CharField(choices=[('agenda', 'Agenda'), ('budget', 'Budget'), ('invitation', 'Invitation'), ('other', 'Other')], default='document', max_length=20),
        ),
    ]
