# Generated by Django 5.2.7 on 2025-10-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0014_alter_sessionattachment_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='role',
            field=models.CharField(choices=[('chairperson', 'Chairperson'), ('vice_chairperson', 'Vice Chairperson'), ('member', 'Member'), ('substitute_member', 'Substitute Member')], default='member', help_text='Role of the user in the committee', max_length=20),
        ),
    ]
