# Generated by Django 5.2.7 on 2025-12-05 08:06

from django.db import migrations, models


def convert_postponed_to_invited(apps, schema_editor):
    """Convert existing 'postponed' sessions to 'invited'"""
    Session = apps.get_model('local', 'Session')
    Session.objects.filter(status='postponed').update(status='invited')


def reverse_convert_invited_to_postponed(apps, schema_editor):
    """Reverse migration: convert 'invited' back to 'postponed'"""
    Session = apps.get_model('local', 'Session')
    Session.objects.filter(status='invited').update(status='postponed')


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0015_add_substitute_member_role'),
    ]

    operations = [
        # Data migration: convert postponed to invited
        migrations.RunPython(convert_postponed_to_invited, reverse_convert_invited_to_postponed),
        # Schema migration: update the field choices
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('invited', 'Invited')], default='scheduled', help_text='Current status of the session', max_length=20),
        ),
    ]
