# Generated by Django 5.2.7 on 2025-12-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0016_replace_postponed_with_invited_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='abbreviation',
            field=models.CharField(blank=True, help_text="Abbreviation for the committee (e.g., 'BA' for Budgetausschuss)", max_length=20),
        ),
    ]
