# Generated by Django 5.2.7 on 2025-12-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0017_add_committee_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('regular', 'Regular Session'), ('special', 'Special Session'), ('inaugural', 'Inaugural Session')], default='regular', help_text='Type of session', max_length=20),
        ),
    ]

