# Generated by Django 5.2.7 on 2025-12-11 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0018_add_inaugural_session_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_count', models.PositiveIntegerField(default=0, help_text='Number of present members from this party')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_presence', to='local.party')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_records', to='local.session')),
            ],
            options={
                'verbose_name': 'Session Presence',
                'verbose_name_plural': 'Session Presences',
                'ordering': ['party__name'],
                'unique_together': {('session', 'party')},
            },
        ),
    ]
