# Generated by Django 5.2.9 on 2025-12-19 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0019_sessionpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='committee',
            field=models.ForeignKey(blank=True, help_text='Committee this session belongs to (optional, for committee meetings)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='local.committee'),
        ),
    ]
