# Generated by Django 5.2.9

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0020_add_committee_to_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or name of the meeting', max_length=200)),
                ('scheduled_date', models.DateTimeField(help_text='Date and time when the meeting is scheduled')),
                ('location', models.CharField(blank=True, help_text='Location where the meeting will be held', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Description or agenda of the meeting')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the meeting is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.JSONField(blank=True, default=dict)),
                ('committee', models.ForeignKey(help_text='Committee holding the meeting', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='local.committee')),
            ],
            options={
                'verbose_name': 'Committee Meeting',
                'verbose_name_plural': 'Committee Meetings',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
