# Generated by Django 6.0.1 on 2026-01-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0022_alter_committeemeeting_history_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemeeting',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title or name of the meeting (set automatically on create: committee name + date)', max_length=200),
        ),
    ]
