# Generated by Django 6.0.1 on 2026-01-31 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0023_alter_committeemeeting_title_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeemeeting',
            name='history',
        ),
    ]
