# Generated by Django 6.0.1 on 2026-01-31 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0024_remove_committeemeeting_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Term this committee belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees', to='local.term'),
        ),
    ]
