# Generated by Django 6.0.1 on 2026-01-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0028_alter_session_title_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title of the session (set automatically on create: Bezirksvertretungssitzung + date)', max_length=200),
        ),
    ]
