# Generated by Django 6.0.2 on 2026-02-20 21:23

from django.db import migrations, models


def migrate_budget_to_minutes(apps, schema_editor):
    """Migrate existing 'budget' attachments to 'minutes'"""
    CommitteeMeetingAttachment = apps.get_model('local', 'CommitteeMeetingAttachment')
    SessionAttachment = apps.get_model('local', 'SessionAttachment')
    CommitteeMeetingAttachment.objects.filter(file_type='budget').update(file_type='minutes')
    SessionAttachment.objects.filter(file_type='budget').update(file_type='minutes')


def reverse_migrate(apps, schema_editor):
    """Revert: change 'minutes' back to 'budget' (only for those that were budget)"""
    pass  # Cannot reliably reverse


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0033_merge_20260202_1418'),
    ]

    operations = [
        migrations.RunPython(migrate_budget_to_minutes, reverse_migrate),
        migrations.AlterField(
            model_name='committeemeetingattachment',
            name='file_type',
            field=models.CharField(choices=[('agenda', 'Agenda'), ('invitation', 'Invitation'), ('minutes', 'Minutes'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionattachment',
            name='file_type',
            field=models.CharField(choices=[('agenda', 'Agenda'), ('invitation', 'Invitation'), ('minutes', 'Minutes'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
