# Generated by Django 6.0.2 on 2026-02-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0034_alter_attachment_types_budget_to_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionattachment',
            name='file_type',
            field=models.CharField(choices=[('agenda', 'Agenda'), ('budget', 'Budget'), ('invitation', 'Invitation'), ('minutes', 'Minutes'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
