# Generated by Django 5.2 on 2025-08-29 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local', '0006_party_local_alter_party_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the political group', max_length=200)),
                ('short_name', models.CharField(blank=True, help_text='Short name or abbreviation', max_length=50)),
                ('description', models.TextField(blank=True, help_text="Description of the group's purpose and goals")),
                ('founded_date', models.DateField(blank=True, help_text='Date when the group was founded', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the group is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.JSONField(blank=True, default=dict)),
                ('party', models.ForeignKey(help_text='Party this group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='local.party')),
            ],
            options={
                'verbose_name': 'Political Group',
                'verbose_name_plural': 'Political Groups',
                'ordering': ['name'],
                'unique_together': {('name', 'party')},
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('leader', 'Leader'), ('deputy_leader', 'Deputy Leader'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('board_member', 'Board Member')], default='member', help_text='Role of the user in the group', max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True, help_text='Date when the user joined the group')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the membership is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the membership')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.JSONField(blank=True, default=dict)),
                ('group', models.ForeignKey(help_text='Group the user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='group.group')),
                ('user', models.ForeignKey(help_text='User who is a member', on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Member',
                'verbose_name_plural': 'Group Members',
                'ordering': ['-joined_date'],
                'unique_together': {('user', 'group')},
            },
        ),
    ]
