# Generated by Django 5.2 on 2025-08-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('leader', 'Leader'), ('deputy_leader', 'Deputy Leader'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('board_member', 'Board Member'), ('admin', 'Group Admin')], default='member', help_text='Role of the user in the group', max_length=20),
        ),
    ]
