# Generated by Django 5.2 on 2025-08-30 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_groupmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when the user joined the group'),
        ),
    ]
