# Generated by Django 5.2 on 2025-08-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_groupmember_joined_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('member', 'Member'), ('leader', 'Leader'), ('deputy_leader', 'Deputy Leader'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('board_member', 'Board Member'), ('admin', 'Group Admin')], help_text='Name of the role', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the role')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group Role',
                'verbose_name_plural': 'Group Roles',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='role',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='roles',
            field=models.ManyToManyField(help_text='Roles of the user in the group', related_name='memberships', to='group.grouprole'),
        ),
    ]
