# Generated by Django 5.2 on 2025-08-30 18:01

from django.db import migrations


def create_default_roles(apps, schema_editor):
    """Create default group roles"""
    GroupRole = apps.get_model('group', 'GroupRole')
    
    # Create default roles
    roles_data = [
        ('member', 'Member'),
        ('leader', 'Leader'),
        ('deputy_leader', 'Deputy Leader'),
        ('secretary', 'Secretary'),
        ('treasurer', 'Treasurer'),
        ('board_member', 'Board Member'),
        ('admin', 'Group Admin'),
    ]
    
    for role_name, role_display in roles_data:
        GroupRole.objects.get_or_create(
            name=role_name,
            defaults={
                'description': f'Default {role_display} role',
                'is_active': True
            }
        )


def migrate_existing_roles(apps, schema_editor):
    """Migrate existing single roles to the new many-to-many system"""
    GroupMember = apps.get_model('group', 'GroupMember')
    GroupRole = apps.get_model('group', 'GroupRole')
    
    # Get the old role field data (this will be available during migration)
    # We need to handle this carefully since the field is being removed
    
    # For now, we'll just ensure all members have at least the 'member' role
    member_role = GroupRole.objects.filter(name='member').first()
    if member_role:
        for group_member in GroupMember.objects.all():
            if not group_member.roles.exists():
                group_member.roles.add(member_role)


def reverse_migrate_roles(apps, schema_editor):
    """Reverse migration - remove all roles"""
    GroupRole = apps.get_model('group', 'GroupRole')
    GroupRole.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_grouprole_remove_groupmember_role_groupmember_roles'),
    ]

    operations = [
        migrations.RunPython(create_default_roles, reverse_migrate_roles),
        migrations.RunPython(migrate_existing_roles, migrations.RunPython.noop),
    ]
