# Generated by Django 5.2 on 2025-08-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_create_default_roles'),
        ('user', '0002_role_alter_customuser_options_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupRole',
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='roles',
            field=models.ManyToManyField(help_text='Roles of the user in the group', related_name='group_memberships', to='user.role'),
        ),
    ]
