# Generated by Django 5.2 on 2025-08-30 18:18

from django.db import migrations


def create_group_roles(apps, schema_editor):
    """Create group roles in the user app's Role model"""
    Role = apps.get_model('user', 'Role')
    
    # Create group roles
    group_roles = [
        ('Group Admin', 'Group administration role with full management permissions'),
        ('Leader', 'Group leadership role with decision-making authority'),
        ('Deputy Leader', 'Deputy leadership role supporting the leader'),
        ('Secretary', 'Secretary role for documentation and communication'),
        ('Treasurer', 'Treasurer role for financial management'),
        ('Board Member', 'Board member role for organizational governance'),
        ('Member', 'Basic group membership role'),
    ]
    
    for role_name, role_description in group_roles:
        Role.objects.get_or_create(
            name=role_name,
            defaults={
                'description': role_description,
                'is_active': True,
                'permissions': {'permissions': []}
            }
        )


def reverse_create_group_roles(apps, schema_editor):
    """Reverse migration - remove group roles"""
    Role = apps.get_model('user', 'Role')
    
    group_role_names = [
        'Group Admin', 'Leader', 'Deputy Leader', 'Secretary', 
        'Treasurer', 'Board Member', 'Member'
    ]
    
    Role.objects.filter(name__in=group_role_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_delete_grouprole_alter_groupmember_roles'),
    ]

    operations = [
        migrations.RunPython(create_group_roles, reverse_create_group_roles),
    ]
