# Generated by Django 5.2 on 2025-08-30 18:49

from django.db import migrations


def remove_secretary_treasurer_roles(apps, schema_editor):
    """Remove Secretary and Treasurer roles from the system"""
    Role = apps.get_model('user', 'Role')
    GroupMember = apps.get_model('group', 'GroupMember')
    
    # Remove Secretary and Treasurer roles from all members
    secretary_role = Role.objects.filter(name='Secretary').first()
    treasurer_role = Role.objects.filter(name='Treasurer').first()
    
    if secretary_role:
        # Remove secretary role from all members
        for member in GroupMember.objects.filter(roles=secretary_role):
            member.roles.remove(secretary_role)
        # Delete the secretary role
        secretary_role.delete()
    
    if treasurer_role:
        # Remove treasurer role from all members
        for member in GroupMember.objects.filter(roles=treasurer_role):
            member.roles.remove(treasurer_role)
        # Delete the treasurer role
        treasurer_role.delete()


def reverse_remove_roles(apps, schema_editor):
    """Reverse migration - recreate Secretary and Treasurer roles"""
    Role = apps.get_model('user', 'Role')
    
    # Recreate Secretary role
    Role.objects.get_or_create(
        name='Secretary',
        defaults={
            'description': 'Secretary role for documentation and communication',
            'is_active': True,
            'permissions': {'permissions': []}
        }
    )
    
    # Recreate Treasurer role
    Role.objects.get_or_create(
        name='Treasurer',
        defaults={
            'description': 'Treasurer role for financial management',
            'is_active': True,
            'permissions': {'permissions': []}
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_create_group_roles'),
    ]

    operations = [
        migrations.RunPython(remove_secretary_treasurer_roles, reverse_remove_roles),
    ]
