# Generated by Django 5.2 on 2025-08-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_remove_secretary_treasurer_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='founded_date',
        ),
        migrations.RemoveField(
            model_name='group',
            name='short_name',
        ),
    ]
