# Generated by Django 5.2.7 on 2025-10-06 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_remove_group_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or name of the meeting', max_length=200)),
                ('meeting_type', models.CharField(choices=[('regular', 'Regular Meeting'), ('special', 'Special Meeting'), ('annual', 'Annual Meeting'), ('emergency', 'Emergency Meeting')], default='regular', help_text='Type of meeting', max_length=20)),
                ('scheduled_date', models.DateTimeField(help_text='Date and time when the meeting is scheduled')),
                ('location', models.CharField(blank=True, help_text='Location where the meeting will be held', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Description or agenda of the meeting')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the meeting is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the meeting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Group holding the meeting', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='group.group')),
            ],
            options={
                'verbose_name': 'Group Meeting',
                'verbose_name_plural': 'Group Meetings',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
