# Generated by Django 5.2.7 on 2025-10-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_groupmeeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmeeting',
            name='meeting_type',
        ),
    ]
