# Generated by Django 5.2.7 on 2025-10-06 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_remove_meeting_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the agenda item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description or details of the agenda item')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the agenda item within the meeting')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the agenda item is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the agenda item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agenda_items', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(help_text='Meeting this agenda item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='group.groupmeeting')),
                ('parent_item', models.ForeignKey(blank=True, help_text='Parent agenda item if this is a sub-item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='group.agendaitem')),
            ],
            options={
                'verbose_name': 'Agenda Item',
                'verbose_name_plural': 'Agenda Items',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
