# Generated by Django 6.0.1 on 2026-01-31 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_add_agenda_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ['-joined_date', '-id'], 'verbose_name': 'Group Member', 'verbose_name_plural': 'Group Members'},
        ),
    ]
