# Generated by Django 6.0.1 on 2026-02-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0019_remove_board_member_and_voter_roles'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupmeetingparticipation',
            name='group_groupmeetingparticipation_meeting_member_uniq',
        ),
        migrations.AlterUniqueTogether(
            name='groupmeetingparticipation',
            unique_together={('meeting', 'member')},
        ),
    ]
