# Generated by Django 6.0.2 on 2026-02-18 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0020_remove_groupmeetingparticipation_group_groupmeetingparticipation_meeting_member_uniq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event', max_length=200)),
                ('scheduled_date', models.DateTimeField(help_text='Date and time of the event')),
                ('location', models.CharField(blank=True, help_text='Location or place of the event', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Optional description or details')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the event is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_events', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Group the event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='group.group')),
            ],
            options={
                'verbose_name': 'Group Event',
                'verbose_name_plural': 'Group Events',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='GroupEventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('will_attend', models.BooleanField(default=False, help_text='Whether the member will attend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Event', on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='group.groupevent')),
                ('member', models.ForeignKey(help_text='Group member', on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='group.groupmember')),
            ],
            options={
                'verbose_name': 'Group Event Participation',
                'verbose_name_plural': 'Group Event Participations',
                'ordering': ['member__user__last_name', 'member__user__first_name'],
                'unique_together': {('event', 'member')},
            },
        ),
    ]
