# Generated by Django 6.1 on 2026-09-03 15:49

import django.db.models.deletion
from django.db import migrations, models


def create_initial_membership_periods(apps, schema_editor):
    GroupMember = apps.get_model('group', 'GroupMember')
    MembershipPeriod = apps.get_model('group', 'MembershipPeriod')
    for member in GroupMember.objects.all().iterator():
        end_date = None
        if not member.is_active:
            end_date = member.updated_at.date() if member.updated_at else member.joined_date
        MembershipPeriod.objects.create(
            member=member,
            start_date=member.joined_date,
            end_date=end_date,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0023_add_groupmeeting_completed_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day of this membership period')),
                ('end_date', models.DateField(blank=True, help_text='Last day of this membership period (leave empty if currently active)', null=True)),
                ('member', models.ForeignKey(help_text='Group membership this period belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='group.groupmember')),
            ],
            options={
                'verbose_name': 'Membership period',
                'verbose_name_plural': 'Membership periods',
                'ordering': ['-start_date', '-pk'],
            },
        ),
        migrations.RunPython(create_initial_membership_periods, migrations.RunPython.noop),
    ]
